[2024-09-12T08:49:10.579+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-09-12T08:49:07.532404+00:00 [queued]>
[2024-09-12T08:49:10.583+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-09-12T08:49:07.532404+00:00 [queued]>
[2024-09-12T08:49:10.583+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-09-12T08:49:10.625+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): one_task> on 2024-09-12 08:49:07.532404+00:00
[2024-09-12T08:49:10.629+0000] {standard_task_runner.py:57} INFO - Started process 12463 to run task
[2024-09-12T08:49:10.631+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2024-09-12T08:49:07.532404+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/one_task.py', '--cfg-path', '/tmp/tmpfr48pgis']
[2024-09-12T08:49:10.632+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask one_task
[2024-09-12T08:49:10.699+0000] {task_command.py:410} INFO - Running <TaskInstance: one_task_dag.one_task manual__2024-09-12T08:49:07.532404+00:00 [running]> on host codespaces-a5bf6d
[2024-09-12T08:49:10.807+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akash' AIRFLOW_CTX_DAG_ID='one_task_dag' AIRFLOW_CTX_TASK_ID='one_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T08:49:07.532404+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T08:49:07.532404+00:00'
[2024-09-12T08:49:10.808+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-12T08:49:10.808+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello, LinkedIn Learning!" > /worksspaces/hands-on-introduction-data-engineering-4395021/lab']
[2024-09-12T08:49:10.815+0000] {subprocess.py:86} INFO - Output:
[2024-09-12T08:49:10.817+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /worksspaces/hands-on-introduction-data-engineering-4395021/lab: No such file or directory
[2024-09-12T08:49:10.818+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-12T08:49:10.823+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-12T08:49:10.825+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20240912T084907, start_date=20240912T084910, end_date=20240912T084910
[2024-09-12T08:49:10.869+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 12463)
[2024-09-12T08:49:10.884+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-09-12T08:49:10.893+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
